### ISSUE TITLE
ObjFlowData.xml is missing

### ISSUE THREAD

**Issue by MichaelHinrichs** [USh-MK78/MK7_3D_KMP_Editor#1]

**Comment by USh-MK78** [comment]
To get ObjFlowData.xml, you need to use "Every File Explorer" to open RaceCommon.szs and export "ObjFlow.bin".

1. Open RaceCommon.szs using Every File Explorer and export "ObjFlow.bin".
2. Move the exported "ObjFlow.bin" to the same directory as MK7_3D_KMP_Editor_For_PG.exe.
3. Start MK7_3D_KMP_Editor_For_PG.exe.
4. Open "ObjFlow Xml Editor" from the "ObjFlow" menu.
5. Click "Yes".
6. ObjFlowData.xml is automatically generated.

**Comment by MichaelHinrichs** [comment]
Hmm. I checked Common.szs, Menu3D.szs, and RaceCommon.szs, already. I must have missed it due to thinking that i was looking for an XML file, and beliving that that the BIN files were useless as they could not be opened by Switch Toolbox.
